[workspace]
resolver = "2"
members = [
    "src/rust/",
    "src/rust/cryptography-cffi",
    "src/rust/cryptography-crypto",
    "src/rust/cryptography-keepalive",
    "src/rust/cryptography-key-parsing",
    "src/rust/cryptography-openssl",
    "src/rust/cryptography-x509",
    "src/rust/cryptography-x509-verification",
]

[workspace.package]
version = "0.1.0"
authors = ["The cryptography developers <cryptography-dev@python.org>"]
edition = "2021"
publish = false
# This specifies the MSRV
rust-version = "1.65.0"

[workspace.dependencies]
asn1 = { version = "0.20.0", default-features = false }
pyo3 = { version = "0.23.5", features = ["abi3"] }
openssl = { version = "0.10.71", git = "https://github.com/sfackler/rust-openssl.git", rev = "7c7b2e6c9f95e77e56ab37af70b16de75beff387" }
openssl-sys = { version = "0.9.104", git = "https://github.com/sfackler/rust-openssl.git", rev = "7c7b2e6c9f95e77e56ab37af70b16de75beff387" }

[profile.release]
overflow-checks = true
